server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: pms-route # 商品管理路由
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: oms-route # 订单管理路由
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums-route # 用户管理路由
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route # 仓库管理路由
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: sms-route # 营销管理路由
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: search-route # 网关路由
          uri: lb://search-service
          predicates:
            - Host=search.gmall.com
        - id: index-route1 # 首页的同步请求路由
          uri: lb://index-service
          predicates:
            - Host=www.gmall.com
#          filters:
#            - Auth=/
          # - Path=/index/**  如果写在一个里面，他们的关系是and关系
        - id: index-route2 # 首页的异步请求路由
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: item-route
          uri: lb://item-service
          predicates:
            - Path=/item/**
        - id: auth-route # 单点登陆路由
          uri: lb://auth-service
          predicates:
            - Host=sso.gmall.com
        - id: cart-route
          uri: lb://cart-service
          predicates:
            - Host=cart.gmall.com
      x-forwarded:
        enabled: true
  redis:
    host: 192.168.181.128
    password: 123456

auth:
  jwt: # 请自己完成配置到配置中心
    pubKeyPath: E:\workspace\java\guli-mall-server\rsa.pub
    cookieName: GMALL-TOKEN

